CC=g++
Vector: VectorApdorjimas.o funkcijos.o
	$(CC) -o Vector VectorApdorjimas.o funkcijos.o
Deque: DeQueApdorojimas.o Dequefunkcijos.o
	$(CC) -o Deque DeQueApdorjimas.o Dequefunkcijos.o
List: ListApdorojimas.o Listfunkcijos.o
	$(CC) -o List ListApdorojimas.o Listfunkcijos.o
GenerateFile: SarasoGen.o
	$(CC) -o GenerateFile SarasoGen.o
clean:
	rm *.o Vector Deque List *.txt
